# Generated by Django 4.1.7 on 2023-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=32)),
                ('Middle_Name', models.CharField(max_length=32)),
                ('Last_Name', models.CharField(max_length=32)),
                ('User_id', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6)),
                ('Age', models.IntegerField(max_length=3)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
