# Generated by Django 4.1.7 on 2023-02-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('tweet', models.TextField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
    ]
